version: "3.8"

services:
  web:
    build: .
    environment:
      - DATABASE_URL=sqlite:///./database/database.db
    ports:
      - "${PORT}:8000"
    volumes:
      - ./database:/app/database
    env_file:
      - .env
